require('fractals/plugins')
require('fractals/autocmds')
require('fractals/lsp')
require('fractals/colorscheme')
require('fractals/editor')
require('fractals/filebrowsing')
require('fractals/options')
